name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ us-east-1 }} | docker login --username AWS --password-stdin ${{ 154075864419 }}.dkr.ecr.${{ us-east-1 }}.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t ${{ 154075864419 }}.dkr.ecr.${{ us-east-1 }}.amazonaws.com/my-node-app:latest .
        docker push ${{ 154075864419 }}.dkr.ecr.${{ us-east-1 }}.amazonaws.com/my-node-app:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
